"""
SOAC TensorRT Demo Templates
============================

Template strings for TensorRT PC demo generation.
"""

# =============================================================================
# PYTHON INFERENCE SCRIPT
# =============================================================================

RUN_INFERENCE_PY = '''#!/usr/bin/env python3
"""
SOAC TensorRT Demo - Inference Script

This script demonstrates inference using the optimized TensorRT engine.
Generated by SOAC (Self-Optimizing AI Compiler).

Requirements:
    - NVIDIA GPU with CUDA support
    - TensorRT 8.x or later
    - pycuda or cuda-python

Usage:
    python run_inference.py
"""

import numpy as np
import time
import sys

# TensorRT imports
try:
    import tensorrt as trt
    TRT_AVAILABLE = True
except ImportError:
    print("ERROR: TensorRT not available.")
    print("Please install TensorRT: https://developer.nvidia.com/tensorrt")
    sys.exit(1)

# CUDA memory management
try:
    from cuda.bindings import runtime as cudart
    CUDA_AVAILABLE = True
    USE_PYCUDA = False
except ImportError:
    try:
        import pycuda.driver as cuda
        import pycuda.autoinit
        CUDA_AVAILABLE = True
        USE_PYCUDA = True
    except ImportError:
        print("ERROR: No CUDA Python bindings found.")
        print("Install: pip install cuda-python  OR  pip install pycuda")
        sys.exit(1)


# Model configuration
MODEL_PATH = "model.plan"
INPUT_SHAPE = {input_shape}
OUTPUT_SHAPE = {output_shape}


class TRTInference:
    """TensorRT inference wrapper."""
    
    def __init__(self, engine_path: str):
        """Load TensorRT engine."""
        self.logger = trt.Logger(trt.Logger.WARNING)
        
        # Load engine
        with open(engine_path, "rb") as f:
            engine_data = f.read()
        
        self.runtime = trt.Runtime(self.logger)
        self.engine = self.runtime.deserialize_cuda_engine(engine_data)
        self.context = self.engine.create_execution_context()
        
        # Allocate buffers
        self._allocate_buffers()
        
        print(f"Loaded TensorRT engine: {{engine_path}}")
        print(f"  Input shape: {{INPUT_SHAPE}}")
        print(f"  Output shape: {{OUTPUT_SHAPE}}")
    
    def _allocate_buffers(self):
        """Allocate GPU memory for input/output."""
        self.inputs = []
        self.outputs = []
        self.bindings = []
        self.stream = None
        
        if USE_PYCUDA:
            self.stream = cuda.Stream()
        else:
            _, self.stream = cudart.cudaStreamCreate()
        
        for i in range(self.engine.num_io_tensors):
            name = self.engine.get_tensor_name(i)
            dtype = trt.nptype(self.engine.get_tensor_dtype(name))
            shape = self.engine.get_tensor_shape(name)
            size = np.prod(shape) * np.dtype(dtype).itemsize
            
            # Allocate device memory
            if USE_PYCUDA:
                device_mem = cuda.mem_alloc(int(size))
            else:
                _, device_mem = cudart.cudaMalloc(int(size))
            
            binding = {{
                "name": name,
                "dtype": dtype,
                "shape": tuple(shape),
                "device": device_mem,
                "host": np.empty(shape, dtype=dtype),
            }}
            
            if self.engine.get_tensor_mode(name) == trt.TensorIOMode.INPUT:
                self.inputs.append(binding)
            else:
                self.outputs.append(binding)
        
        # Set tensor addresses
        for inp in self.inputs:
            addr = inp["device"] if USE_PYCUDA else inp["device"]
            self.context.set_tensor_address(inp["name"], int(addr))
        for out in self.outputs:
            addr = out["device"] if USE_PYCUDA else out["device"]
            self.context.set_tensor_address(out["name"], int(addr))
    
    def infer(self, input_data: np.ndarray) -> np.ndarray:
        """Run inference."""
        # Copy input to device
        inp = self.inputs[0]
        inp["host"] = input_data.astype(inp["dtype"])
        
        if USE_PYCUDA:
            cuda.memcpy_htod_async(inp["device"], inp["host"], self.stream)
        else:
            cudart.cudaMemcpyAsync(
                inp["device"], inp["host"].ctypes.data,
                inp["host"].nbytes, cudart.cudaMemcpyKind.cudaMemcpyHostToDevice,
                self.stream
            )
        
        # Execute
        self.context.execute_async_v3(stream_handle=int(self.stream) if USE_PYCUDA else self.stream)
        
        # Copy output to host
        out = self.outputs[0]
        if USE_PYCUDA:
            cuda.memcpy_dtoh_async(out["host"], out["device"], self.stream)
            self.stream.synchronize()
        else:
            cudart.cudaMemcpyAsync(
                out["host"].ctypes.data, out["device"],
                out["host"].nbytes, cudart.cudaMemcpyKind.cudaMemcpyDeviceToHost,
                self.stream
            )
            cudart.cudaStreamSynchronize(self.stream)
        
        return out["host"].copy()


def main():
    """Run demo inference."""
    print("=" * 60)
    print("SOAC TensorRT Demo")
    print("=" * 60)
    
    # Load engine
    engine = TRTInference(MODEL_PATH)
    
    # Create dummy input
    input_data = np.random.rand(*INPUT_SHAPE).astype(np.float32)
    print(f"\\nInput shape: {{input_data.shape}}")
    
    # Warmup
    print("\\nWarming up...")
    for _ in range(10):
        engine.infer(input_data)
    
    # Benchmark
    print("\\nRunning benchmark (100 iterations)...")
    latencies = []
    for _ in range(100):
        start = time.perf_counter()
        output = engine.infer(input_data)
        end = time.perf_counter()
        latencies.append((end - start) * 1000)
    
    # Results
    print(f"\\nResults:")
    print(f"  Mean latency: {{np.mean(latencies):.2f}} ms")
    print(f"  Std latency:  {{np.std(latencies):.2f}} ms")
    print(f"  Min latency:  {{np.min(latencies):.2f}} ms")
    print(f"  Max latency:  {{np.max(latencies):.2f}} ms")
    print(f"  Output shape: {{output.shape}}")
    print(f"  Output range: [{{output.min():.4f}}, {{output.max():.4f}}]")
    
    print("\\n" + "=" * 60)
    print("Demo complete!")


if __name__ == "__main__":
    main()
'''

# =============================================================================
# REQUIREMENTS
# =============================================================================

REQUIREMENTS_TXT = '''# TensorRT Demo Requirements
numpy>=1.20.0
tensorrt>=8.0.0

# CUDA Python bindings (choose one)
# Option 1: cuda-python (recommended)
cuda-python>=12.0.0

# Option 2: pycuda (alternative)
# pycuda>=2022.1
'''

# =============================================================================
# README (AVAILABLE)
# =============================================================================

README_AVAILABLE_MD = '''# SOAC TensorRT Demo

This is a ready-to-run TensorRT demo generated by **SOAC (Self-Optimizing AI Compiler)**.

## Model Details

- **Model**: {model_name}
- **Format**: TensorRT Engine (.plan)
- **Precision**: {precision}
- **Size**: {model_size_mb:.2f} MB
- **Generated**: {timestamp}

## Quick Start

```bash
# Install dependencies
pip install -r requirements.txt

# Run inference
python run_inference.py
```

## Files

| File | Description |
|------|-------------|
| `model.plan` | Optimized TensorRT engine |
| `run_inference.py` | Inference demo script |
| `requirements.txt` | Python dependencies |

## Requirements

- NVIDIA GPU with CUDA support
- CUDA Toolkit 11.x or 12.x
- TensorRT 8.x or later
- Python 3.8+

## Generated by SOAC

This demo was automatically generated by SOAC to showcase GPU inference.
'''

# =============================================================================
# STUB (UNAVAILABLE)
# =============================================================================

UNAVAILABLE_MD = '''# TensorRT Demo - UNAVAILABLE

## Why is this unavailable?

TensorRT demo generation requires:

1. **NVIDIA GPU** - Not detected on the build machine
2. **TensorRT SDK** - Not installed or not accessible
3. **CUDA Toolkit** - Required for GPU computation

## What you got instead

This stub package contains:
- This explanation document
- Setup guide for enabling TensorRT
- Requirements file for when you set up GPU

## How to enable TensorRT demos

### Option 1: Use a GPU-enabled machine

Re-run SOAC on a machine with:
- NVIDIA GPU (compute capability 5.0+)
- CUDA Toolkit 11.x or 12.x
- TensorRT 8.x or later

### Option 2: Build the engine yourself

1. Take the ONNX model from the artifacts
2. Install TensorRT on your GPU machine
3. Build the engine:

```bash
trtexec --onnx=model.onnx --saveEngine=model.plan --fp16
```

4. Use the inference script from this package

## Generated by SOAC

SOAC explicitly documents unavailability instead of silently skipping.
Contact: Check SOAC documentation for GPU requirements.
'''

SETUP_GUIDE_MD = '''# TensorRT Setup Guide

## Step 1: Verify GPU

```bash
nvidia-smi
```

You should see your NVIDIA GPU listed with CUDA version.

## Step 2: Install CUDA Toolkit

Download from: https://developer.nvidia.com/cuda-toolkit

```bash
# Ubuntu/Debian
sudo apt install cuda-toolkit-12-0

# Or use conda
conda install cudatoolkit=12.0
```

## Step 3: Install TensorRT

Download from: https://developer.nvidia.com/tensorrt

```bash
# pip install (easiest)
pip install tensorrt

# Or from .tar.gz (more control)
tar -xzf TensorRT-8.x.x.x.tar.gz
pip install TensorRT-8.x.x.x/python/tensorrt-*-cp3*-linux_x86_64.whl
```

## Step 4: Install Python bindings

```bash
pip install cuda-python
# OR
pip install pycuda
```

## Step 5: Verify

```python
import tensorrt as trt
print(f"TensorRT: {trt.__version__}")
```

## Converting ONNX to TensorRT

```bash
# Using trtexec
trtexec --onnx=model.onnx --saveEngine=model.plan --fp16

# Using Python
import tensorrt as trt

logger = trt.Logger(trt.Logger.INFO)
builder = trt.Builder(logger)
network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
parser = trt.OnnxParser(network, logger)

with open("model.onnx", "rb") as f:
    parser.parse(f.read())

config = builder.create_builder_config()
config.set_flag(trt.BuilderFlag.FP16)

engine = builder.build_serialized_network(network, config)
with open("model.plan", "wb") as f:
    f.write(engine)
```
'''
