"""
SOAC Android Demo Templates
===========================

Template strings for Android Studio project generation.
"""

# =============================================================================
# MAIN ACTIVITY
# =============================================================================

MAIN_ACTIVITY_JAVA = '''package com.soac.demo;

import android.content.res.AssetFileDescriptor;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.os.Bundle;
import android.util.Log;
import android.widget.TextView;
import android.widget.ImageView;
import android.widget.Button;
import androidx.appcompat.app.AppCompatActivity;

import org.tensorflow.lite.Interpreter;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.MappedByteBuffer;
import java.nio.channels.FileChannel;
import java.util.Arrays;

/**
 * SOAC Demo - TFLite Inference Example
 * 
 * This demo loads the optimized TFLite model and runs inference.
 * Generated by SOAC (Self-Optimizing AI Compiler).
 */
public class MainActivity extends AppCompatActivity {{
    
    private static final String TAG = "SOACDemo";
    private static final String MODEL_PATH = "model.tflite";
    
    // Model configuration
    private static final int INPUT_SIZE = {input_size};
    private static final int NUM_CLASSES = {num_classes};
    
    private Interpreter tflite;
    private TextView resultText;
    private TextView statusText;
    private Button runButton;
    
    @Override
    protected void onCreate(Bundle savedInstanceState) {{
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        
        resultText = findViewById(R.id.result_text);
        statusText = findViewById(R.id.status_text);
        runButton = findViewById(R.id.run_button);
        
        // Load model
        try {{
            tflite = new Interpreter(loadModelFile());
            statusText.setText("Model loaded successfully!");
            Log.i(TAG, "TFLite model loaded");
        }} catch (IOException e) {{
            statusText.setText("Error loading model: " + e.getMessage());
            Log.e(TAG, "Failed to load model", e);
            return;
        }}
        
        // Run inference button
        runButton.setOnClickListener(v -> runInference());
    }}
    
    /**
     * Load TFLite model from assets.
     */
    private MappedByteBuffer loadModelFile() throws IOException {{
        AssetFileDescriptor fileDescriptor = getAssets().openFd(MODEL_PATH);
        FileInputStream inputStream = new FileInputStream(fileDescriptor.getFileDescriptor());
        FileChannel fileChannel = inputStream.getChannel();
        long startOffset = fileDescriptor.getStartOffset();
        long declaredLength = fileDescriptor.getDeclaredLength();
        return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);
    }}
    
    /**
     * Run inference with dummy input.
     */
    private void runInference() {{
        if (tflite == null) {{
            resultText.setText("Model not loaded!");
            return;
        }}
        
        // Create dummy input (random values 0-1)
        float[][][][] input = new float[1][INPUT_SIZE][INPUT_SIZE][3];
        for (int i = 0; i < INPUT_SIZE; i++) {{
            for (int j = 0; j < INPUT_SIZE; j++) {{
                for (int k = 0; k < 3; k++) {{
                    input[0][i][j][k] = (float) Math.random();
                }}
            }}
        }}
        
        // Output buffer
        float[][] output = new float[1][NUM_CLASSES];
        
        // Run inference
        long startTime = System.nanoTime();
        tflite.run(input, output);
        long endTime = System.nanoTime();
        
        // Calculate latency
        float latencyMs = (endTime - startTime) / 1_000_000.0f;
        
        // Find top prediction
        int topClass = 0;
        float topScore = output[0][0];
        for (int i = 1; i < NUM_CLASSES; i++) {{
            if (output[0][i] > topScore) {{
                topScore = output[0][i];
                topClass = i;
            }}
        }}
        
        // Display results
        String result = String.format(
            "Inference completed!\\n\\n" +
            "Latency: %.2f ms\\n" +
            "Top Class: %d\\n" +
            "Confidence: %.2f%%",
            latencyMs, topClass, topScore * 100
        );
        resultText.setText(result);
        Log.i(TAG, "Inference: " + latencyMs + "ms, class=" + topClass);
    }}
    
    @Override
    protected void onDestroy() {{
        super.onDestroy();
        if (tflite != null) {{
            tflite.close();
        }}
    }}
}}
'''

# =============================================================================
# LAYOUT XML
# =============================================================================

ACTIVITY_MAIN_XML = '''<?xml version="1.0" encoding="utf-8"?>
<LinearLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:padding="24dp"
    android:gravity="center">

    <TextView
        android:id="@+id/title_text"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="SOAC Demo"
        android:textSize="32sp"
        android:textStyle="bold"
        android:layout_marginBottom="16dp"/>
    
    <TextView
        android:id="@+id/subtitle_text"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="TFLite Inference Example"
        android:textSize="16sp"
        android:textColor="#666666"
        android:layout_marginBottom="32dp"/>
    
    <TextView
        android:id="@+id/status_text"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Loading model..."
        android:textSize="14sp"
        android:layout_marginBottom="24dp"/>
    
    <Button
        android:id="@+id/run_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Run Inference"
        android:textSize="16sp"
        android:padding="16dp"
        android:layout_marginBottom="32dp"/>
    
    <TextView
        android:id="@+id/result_text"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Results will appear here"
        android:textSize="16sp"
        android:textAlignment="center"
        android:padding="16dp"
        android:background="#F5F5F5"/>

</LinearLayout>
'''

# =============================================================================
# ANDROID MANIFEST
# =============================================================================

ANDROID_MANIFEST_XML = '''<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.soac.demo">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="SOAC Demo"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.SOACDemo">
        
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        
    </application>

</manifest>
'''

# =============================================================================
# GRADLE FILES
# =============================================================================

APP_BUILD_GRADLE = '''plugins {
    id 'com.android.application'
}

android {
    namespace 'com.soac.demo'
    compileSdk 34

    defaultConfig {
        applicationId "com.soac.demo"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    
    // Don't compress tflite files
    aaptOptions {
        noCompress "tflite"
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    
    // TensorFlow Lite
    implementation 'org.tensorflow:tensorflow-lite:2.14.0'
    implementation 'org.tensorflow:tensorflow-lite-support:0.4.4'
    
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
'''

PROJECT_BUILD_GRADLE = '''// Top-level build file
plugins {
    id 'com.android.application' version '8.2.0' apply false
}
'''

SETTINGS_GRADLE = '''pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "SOACDemo"
include ':app'
'''

GRADLE_PROPERTIES = '''# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
'''

# =============================================================================
# README
# =============================================================================

README_MD = '''# SOAC Android Demo

This is a ready-to-run Android demo generated by **SOAC (Self-Optimizing AI Compiler)**.

## Model Details

- **Model**: {model_name}
- **Format**: TensorFlow Lite
- **Quantization**: {quantization}
- **Size**: {model_size_mb:.2f} MB
- **Generated**: {timestamp}

## Getting Started

1. **Open in Android Studio**
   - File → Open → Select this folder
   - Wait for Gradle sync to complete

2. **Build and Run**
   - Connect an Android device or start an emulator
   - Click "Run" (green play button)

3. **Test Inference**
   - Tap "Run Inference" button
   - View latency and results

## Project Structure

```
app/
├── src/main/
│   ├── java/com/soac/demo/
│   │   └── MainActivity.java    # Inference code
│   ├── assets/
│   │   └── model.tflite         # Optimized model
│   └── res/layout/
│       └── activity_main.xml    # UI layout
└── build.gradle                 # Dependencies
```

## Requirements

- Android Studio Arctic Fox or later
- Android SDK 24+
- JDK 8+

## Generated by SOAC

This demo was automatically generated by SOAC to showcase the optimized model.
For more information, visit the SOAC documentation.
'''
